/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CacibModal {
        /**
          * Whether the modal is open or not
          * @default false
         */
        "isOpen": boolean;
        /**
          * The title of the modal
          * @default ''
         */
        "modalTitle": string;
        /**
          * Whether the primary button is disabled
          * @default false
         */
        "primaryButtonDisabled": boolean;
        /**
          * Text for the primary action button
          * @default 'Confirmer'
         */
        "primaryButtonText": string;
        /**
          * Text for the secondary action button (cancel)
          * @default 'Annuler'
         */
        "secondaryButtonText": string;
        /**
          * Whether to show the close button (X)
          * @default true
         */
        "showCloseButton": boolean;
        /**
          * The subtitle or description of the modal
          * @default ''
         */
        "subtitle": string;
    }
    interface CacibModalDemo {
        "openBasicModal": () => Promise<void>;
        "openConfirmModal": () => Promise<void>;
        "openContentModal": () => Promise<void>;
        "openNoCloseModal": () => Promise<void>;
    }
}
export interface CacibModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCacibModalElement;
}
declare global {
    interface HTMLCacibModalElementEventMap {
        "modalClose": void;
        "modalPrimaryAction": void;
        "modalSecondaryAction": void;
    }
    interface HTMLCacibModalElement extends Components.CacibModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCacibModalElementEventMap>(type: K, listener: (this: HTMLCacibModalElement, ev: CacibModalCustomEvent<HTMLCacibModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCacibModalElementEventMap>(type: K, listener: (this: HTMLCacibModalElement, ev: CacibModalCustomEvent<HTMLCacibModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCacibModalElement: {
        prototype: HTMLCacibModalElement;
        new (): HTMLCacibModalElement;
    };
    interface HTMLCacibModalDemoElement extends Components.CacibModalDemo, HTMLStencilElement {
    }
    var HTMLCacibModalDemoElement: {
        prototype: HTMLCacibModalDemoElement;
        new (): HTMLCacibModalDemoElement;
    };
    interface HTMLElementTagNameMap {
        "cacib-modal": HTMLCacibModalElement;
        "cacib-modal-demo": HTMLCacibModalDemoElement;
    }
}
declare namespace LocalJSX {
    interface CacibModal {
        /**
          * Whether the modal is open or not
          * @default false
         */
        "isOpen"?: boolean;
        /**
          * The title of the modal
          * @default ''
         */
        "modalTitle"?: string;
        /**
          * Event emitted when modal is closed
         */
        "onModalClose"?: (event: CacibModalCustomEvent<void>) => void;
        /**
          * Event emitted when primary button is clicked
         */
        "onModalPrimaryAction"?: (event: CacibModalCustomEvent<void>) => void;
        /**
          * Event emitted when secondary button is clicked
         */
        "onModalSecondaryAction"?: (event: CacibModalCustomEvent<void>) => void;
        /**
          * Whether the primary button is disabled
          * @default false
         */
        "primaryButtonDisabled"?: boolean;
        /**
          * Text for the primary action button
          * @default 'Confirmer'
         */
        "primaryButtonText"?: string;
        /**
          * Text for the secondary action button (cancel)
          * @default 'Annuler'
         */
        "secondaryButtonText"?: string;
        /**
          * Whether to show the close button (X)
          * @default true
         */
        "showCloseButton"?: boolean;
        /**
          * The subtitle or description of the modal
          * @default ''
         */
        "subtitle"?: string;
    }
    interface CacibModalDemo {
    }
    interface IntrinsicElements {
        "cacib-modal": CacibModal;
        "cacib-modal-demo": CacibModalDemo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cacib-modal": LocalJSX.CacibModal & JSXBase.HTMLAttributes<HTMLCacibModalElement>;
            "cacib-modal-demo": LocalJSX.CacibModalDemo & JSXBase.HTMLAttributes<HTMLCacibModalDemoElement>;
        }
    }
}
